# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'kkma', '0001_initial'), (b'kkma', '0002_auto_20160904_0244'), (b'kkma', '0003_auto_20160911_0053'), (b'kkma', '0004_auto_20160916_2027'), (b'kkma', '0005_auto_20160916_2226'), (b'kkma', '0006_auto_20160916_2257'), (b'kkma', '0007_auto_20160916_2320'), (b'kkma', '0008_auto_20160920_2135'), (b'kkma', '0009_auto_20160924_2208'), (b'kkma', '0010_auto_20160925_2311'), (b'kkma', '0011_auto_20161008_0058'), (b'kkma', '0012_auto_20161008_0100')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.CharField(choices=[('JBK', 'JKB'), ('JKS', 'JKS'), ('NNG', 'NNG'), ('NNB', 'NNB'), ('UNT', 'UNT'), ('JKC', 'JKC'), ('MAG', 'MAG')], db_index=True, default='JBK', max_length=5, verbose_name='\ud488\uc0ac')),
                ('ws_type', models.CharField(choices=[('W', '\ubb38\uc5b4'), ('S', '\uad6c\uc5b4')], db_index=True, default='W', max_length=1, verbose_name='\ubb38\uc5b4/\uad6c\uc5b4')),
                ('morpheme', models.CharField(db_index=True, help_text='Keyword', max_length=255, verbose_name='\ud615\ud0dc\uc18c')),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('field_id', models.IntegerField(blank=True, default=0, null=True)),
                ('part_id', models.IntegerField(blank=True, default=0, null=True)),
                ('sent_id', models.IntegerField(blank=True, default=0, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('\ucc98\uc18c', '\ucc98\uc18c'), ('\ucd9c\ubc1c\uc810', '\ucd9c\ubc1c\uc810'), ('\ucd9c\ucc98', '\ucd9c\ucc98'), ('\uadfc\uac70', '\uadfc\uac70'), ('\ube44\uad50\uc758 \uae30\uc900', '\ube44\uad50\uc758 \uae30\uc900'), ('\uc8fc\uc5b4\uc784', '\uc8fc\uc5b4\uc784')], db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ['morpheme', 'ws_type', 'index']},
        ),
        migrations.AlterField(
            model_name='example',
            name='index',
            field=models.PositiveIntegerField(blank=True, help_text='Search Index', null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='word_type',
            field=models.CharField(choices=[('JKB', 'JKB'), ('JKS', 'JKS'), ('NNG', 'NNG'), ('NNB', 'NNB'), ('UNT', 'UNT'), ('JKC', 'JKC'), ('MAG', 'MAG')], db_index=True, default='JKB', help_text='Word type', max_length=5, verbose_name='\ud488\uc0ac'),
        ),
        migrations.AlterField(
            model_name='example',
            name='ws_type',
            field=models.CharField(choices=[('W', '\ubb38\uc5b4'), ('S', '\uad6c\uc5b4')], db_index=True, default='W', help_text='Writing or Spoken', max_length=1, verbose_name='\ubb38\uc5b4/\uad6c\uc5b4'),
        ),
        migrations.AddField(
            model_name='example',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'Not set'), ('\ucc98\uc18c', '\ucc98\uc18c'), ('\ucd9c\ubc1c\uc810', '\ucd9c\ubc1c\uc810'), ('\ucd9c\ucc98', '\ucd9c\ucc98'), ('\uadfc\uac70', '\uadfc\uac70'), ('\ube44\uad50\uc758 \uae30\uc900', '\ube44\uad50\uc758 \uae30\uc900'), ('\uc8fc\uc5b4\uc784', '\uc8fc\uc5b4\uc784'), ('\uae30\ud0c0', '\uae30\ud0c0')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterModelOptions(
            name='example',
            options={},
        ),
        migrations.AlterField(
            model_name='example',
            name='category',
            field=models.CharField(blank=True, choices=[('\ucc98\uc18c', '\ucc98\uc18c'), ('\ucd9c\ubc1c\uc810', '\ucd9c\ubc1c\uc810'), ('\ucd9c\ucc98', '\ucd9c\ucc98'), ('\uadfc\uac70', '\uadfc\uac70'), ('\ube44\uad50\uc758 \uae30\uc900', '\ube44\uad50\uc758 \uae30\uc900'), ('\uc8fc\uc5b4\uc784', '\uc8fc\uc5b4\uc784'), ('\uae30\ud0c0', '\uae30\ud0c0')], db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='phrases',
            field=models.ManyToManyField(related_name='examples', to=b'kkma.Phrase'),
        ),
        migrations.AddField(
            model_name='example',
            name='phrase_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterField(
            model_name='phrase',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='example',
            name='category',
            field=models.CharField(blank=True, choices=[('\ucc98\uc18c', '\ucc98\uc18c'), ('\ucd9c\ubc1c\uc810', '\ucd9c\ubc1c\uc810'), ('\ucd9c\ucc98', '\ucd9c\ucc98'), ('\uadfc\uac70', '\uadfc\uac70'), ('\ube44\uad50\uc758 \uae30\uc900', '\ube44\uad50\uc758 \uae30\uc900'), ('\uc8fc\uc5b4\uc784', '\uc8fc\uc5b4\uc784'), ('\uae30\ud0c0', '\uae30\ud0c0'), ('\ucd94\uc0c1\uc801 \uc7a5\uc18c', '\ucd94\uc0c1\uc801 \uc7a5\uc18c')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='category',
            field=models.CharField(blank=True, choices=[('\ucc98\uc18c', '\ucc98\uc18c'), ('\ucd94\uc0c1\uc801 \uc7a5\uc18c', '\ucd94\uc0c1\uc801 \uc7a5\uc18c'), ('\ucd9c\ubc1c\uc810', '\ucd9c\ubc1c\uc810'), ('\ucd9c\ucc98', '\ucd9c\ucc98'), ('\uadfc\uac70', '\uadfc\uac70'), ('\ube44\uad50\uc758 \uae30\uc900', '\ube44\uad50\uc758 \uae30\uc900'), ('\uc8fc\uc5b4\uc784', '\uc8fc\uc5b4\uc784'), ('\uae30\ud0c0', '\uae30\ud0c0')], db_index=True, max_length=50, null=True),
        )
    ]
