# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.CharField(choices=[('JBK', 'JKB'), ('JKS', 'JKS'), ('NNG', 'NNG'), ('NNB', 'NNB'), ('UNT', 'UNT'), ('JKC', 'JKC'), ('MAG', 'MAG')], db_index=True, default='JBK', max_length=5, verbose_name='\ud488\uc0ac')),
                ('ws_type', models.CharField(choices=[('W', '\ubb38\uc5b4'), ('S', '\uad6c\uc5b4')], db_index=True, default='W', max_length=1, verbose_name='\ubb38\uc5b4/\uad6c\uc5b4')),
                ('morpheme', models.CharField(db_index=True, help_text='Keyword', max_length=255, verbose_name='\ud615\ud0dc\uc18c')),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('field_id', models.IntegerField(blank=True, default=0, null=True)),
                ('part_id', models.IntegerField(blank=True, default=0, null=True)),
                ('sent_id', models.IntegerField(blank=True, default=0, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('\ucc98\uc18c', '\ucc98\uc18c'), ('\ucd9c\ubc1c\uc810', '\ucd9c\ubc1c\uc810'), ('\ucd9c\ucc98', '\ucd9c\ucc98'), ('\uadfc\uac70', '\uadfc\uac70'), ('\ube44\uad50\uc758 \uae30\uc900', '\ube44\uad50\uc758 \uae30\uc900'), ('\uc8fc\uc5b4\uc784', '\uc8fc\uc5b4\uc784')], db_index=True, max_length=50, null=True)),
            ],
        ),
    ]
