# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morpheme', models.CharField(db_index=True, help_text='Keyword', max_length=255, verbose_name='\ud615\ud0dc\uc18c')),
                ('used_in', models.CharField(db_index=True, help_text='Source of example', max_length=255, verbose_name='\uc0ac\uc6a9\uc5ed')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\uc6a9\ub840')),
                ('prefix', models.TextField(blank=True, null=True, verbose_name='\uc120\ud589\uc694\uc18c')),
                ('suffix', models.TextField(blank=True, null=True, verbose_name='\ud6c4\ud589\uc694\uc18c')),
                ('category', models.CharField(blank=True, choices=[('\ucc98\uc18c', '\ucc98\uc18c'), ('\ucd94\uc0c1 \ucc98\uc18c', '\ucd94\uc0c1 \ucc98\uc18c'), ('\ucd9c\ubc1c\uc810', '\ucd9c\ubc1c\uc810'), ('\ucd9c\ucc98', '\ucd9c\ucc98'), ('\uadfc\uac70', '\uadfc\uac70'), ('\ube44\uad50\uc758 \uae30\uc900', '\ube44\uad50\uc758 \uae30\uc900'), ('\uc8fc\uccb4\uc784', '\uc8fc\uccb4\uc784'), ('\uae30\ud0c0', '\uae30\ud0c0')], db_index=True, max_length=50, null=True, verbose_name='\uc758\ubbf8')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(db_index=True, max_length=255)),
                ('count', models.IntegerField(default=1, verbose_name='Total Count')),
            ],
            options={
                'ordering': ('-count',),
            },
        ),
        migrations.AddField(
            model_name='example',
            name='phrases',
            field=models.ManyToManyField(related_name='examples', to='kkma.Phrase'),
        ),
    ]
