# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='prefix',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='\uc120\ud589\uc694\uc18c'),
        ),
        migrations.AlterField(
            model_name='example',
            name='suffix',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='\ud6c4\ud589\uc694\uc18c'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Total Count'),
        ),
    ]
