# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ['morpheme', 'ws_type', 'index']},
        ),
        migrations.AlterField(
            model_name='example',
            name='index',
            field=models.PositiveIntegerField(blank=True, help_text='Search Index', null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='word_type',
            field=models.CharField(choices=[('JKB', 'JKB'), ('JKS', 'JKS'), ('NNG', 'NNG'), ('NNB', 'NNB'), ('UNT', 'UNT'), ('JKC', 'JKC'), ('MAG', 'MAG')], db_index=True, default='JKB', help_text='Word type', max_length=5, verbose_name='\ud488\uc0ac'),
        ),
        migrations.AlterField(
            model_name='example',
            name='ws_type',
            field=models.CharField(choices=[('W', '\ubb38\uc5b4'), ('S', '\uad6c\uc5b4')], db_index=True, default='W', help_text='Writing or Spoken', max_length=1, verbose_name='\ubb38\uc5b4/\uad6c\uc5b4'),
        ),
    ]
