# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkma', '0002_auto_20160904_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'Not set'), ('\ucc98\uc18c', '\ucc98\uc18c'), ('\ucd9c\ubc1c\uc810', '\ucd9c\ubc1c\uc810'), ('\ucd9c\ucc98', '\ucd9c\ucc98'), ('\uadfc\uac70', '\uadfc\uac70'), ('\ube44\uad50\uc758 \uae30\uc900', '\ube44\uad50\uc758 \uae30\uc900'), ('\uc8fc\uc5b4\uc784', '\uc8fc\uc5b4\uc784'), ('\uae30\ud0c0', '\uae30\ud0c0')], db_index=True, max_length=50, null=True),
        ),
    ]
