# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkma', '0004_auto_20160916_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='example',
            name='bold_content',
        ),
        migrations.AddField(
            model_name='example',
            name='phrases',
            field=models.ManyToManyField(to='kkma.Phrase'),
        ),
    ]
