# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkma', '0005_auto_20160916_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='phrase_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
