# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkma', '0006_auto_20160916_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='phrases',
            field=models.ManyToManyField(related_name='examples', to='kkma.Phrase'),
        ),
    ]
