# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkma', '0007_auto_20160916_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterField(
            model_name='phrase',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Total Count'),
        ),
    ]
