# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkma', '0009_auto_20160924_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='category',
            field=models.CharField(blank=True, choices=[('\ucc98\uc18c', '\ucc98\uc18c'), ('\ucd94\uc0c1\uc801 \uc7a5\uc18c', '\ucd94\uc0c1\uc801 \uc7a5\uc18c'), ('\ucd9c\ubc1c\uc810', '\ucd9c\ubc1c\uc810'), ('\ucd9c\ucc98', '\ucd9c\ucc98'), ('\uadfc\uac70', '\uadfc\uac70'), ('\ube44\uad50\uc758 \uae30\uc900', '\ube44\uad50\uc758 \uae30\uc900'), ('\uc8fc\uc5b4\uc784', '\uc8fc\uc5b4\uc784'), ('\uae30\ud0c0', '\uae30\ud0c0')], db_index=True, max_length=50, null=True),
        ),
    ]
