# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkma', '0011_auto_20161008_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
